<?php
/**
 * OffsetWP Twig WordPress Extension
 *
 * @author Jérôme Wohlschlegel
 * @package OffsetWP\Twig\Extension\WordPressExtension
 */

declare( strict_types=1 );

namespace OffsetWP\Twig\Extension\WordPressExtension;

/**
 * The functions of WordPress a template can call by their name, and where each one puts its
 * result.
 *
 * The list is wide on purpose: every function a theme may call from a template to read
 * WordPress, to print its markup, or to queue what the page needs — its scripts, its styles,
 * the state of the Interactivity API —, so that a theme seldom has to reach for fn(). It
 * starts from the functions the starter theme of OffsetWP calls, adds the template tags and
 * the conditional tags the handbook of WordPress lists, the functions the default themes call
 * in their templates and in the helpers of their templates, from Twenty Ten to Twenty
 * Twenty-Five, and the public functions of the template API of wp-includes. Left out on
 * purpose are the functions that set WordPress up rather than render a page with it —
 * add_action(), register_post_type(), update_option() —, the callbacks WordPress hooks to
 * wp_head and wp_footer itself, such as feed_links() or rel_canonical(), the tags the feed and
 * embed templates of WordPress call, such as the_title_rss() or the_excerpt_embed(), the
 * helpers Twig already has under another name, such as wp_parse_args() for merge,
 * locate_template(), which prints the template it loads and returns its path in the same
 * call, two results a template could not both be given, those that live in wp-admin, and the
 * deprecated ones. fn() reaches every one of them all the same.
 *
 * Whether a function prints or returns was read in the source of WordPress, function by
 * function, and not guessed from its name. A function that echoes, includes a file, fires
 * an action or hands its work to a helper that echoes is Result::Printed: get_header() is
 * one, since it includes header.php. One that only computes its result and hands it back is
 * Result::Returned, even when an action it fires on the way could print — the_post() is one,
 * and so is get_the_post_thumbnail() — and so is one that prints into an output buffer of its
 * own and hands back what it printed, as wp_playlist_shortcode() does. Every function exists
 * since WordPress 6.5, which the test suite proves against the stubs of that version, and
 * takes no argument by reference, which Twig could not pass.
 *
 * The groups are the ones the README lists the functions in, in the same order. A function
 * added here is added there as well, which a test asserts.
 */
final class Catalogue {

	/**
	 * Every function, by name, with where it puts its result.
	 *
	 * @var array<string, Result>
	 */
	public const FUNCTIONS = array(
		// The document: its head, its body, and what the site is called and looks like.
		'wp_head'                                => Result::Printed,
		'wp_footer'                              => Result::Printed,
		'wp_body_open'                           => Result::Printed,
		'language_attributes'                    => Result::Printed,
		'get_language_attributes'                => Result::Returned,
		'body_class'                             => Result::Printed,
		'get_body_class'                         => Result::Returned,
		'bloginfo'                               => Result::Printed,
		'get_bloginfo'                           => Result::Returned,
		'wp_get_document_title'                  => Result::Returned,
		'wp_title'                               => Result::Printed,
		'get_locale'                             => Result::Returned,
		'is_rtl'                                 => Result::Returned,
		'site_icon_url'                          => Result::Printed,
		'get_site_icon_url'                      => Result::Returned,
		'has_site_icon'                          => Result::Returned,
		'the_custom_logo'                        => Result::Printed,
		'get_custom_logo'                        => Result::Returned,
		'has_custom_logo'                        => Result::Returned,
		'header_image'                           => Result::Printed,
		'get_header_image'                       => Result::Returned,
		'has_header_image'                       => Result::Returned,
		'the_header_image_tag'                   => Result::Printed,
		'get_header_image_tag'                   => Result::Returned,
		'get_custom_header'                      => Result::Returned,
		'has_custom_header'                      => Result::Returned,
		'the_custom_header_markup'               => Result::Printed,
		'get_custom_header_markup'               => Result::Returned,
		'has_header_video'                       => Result::Returned,
		'is_header_video_active'                 => Result::Returned,
		'the_header_video_url'                   => Result::Printed,
		'get_header_video_url'                   => Result::Returned,
		'display_header_text'                    => Result::Returned,
		'header_textcolor'                       => Result::Printed,
		'get_header_textcolor'                   => Result::Returned,
		'background_image'                       => Result::Printed,
		'get_background_image'                   => Result::Returned,
		'background_color'                       => Result::Printed,
		'get_background_color'                   => Result::Returned,

		// Translation: the gettext functions, those that print and those that escape, and the locales.
		'__'                                     => Result::Returned,
		'_x'                                     => Result::Returned,
		'_n'                                     => Result::Returned,
		'_nx'                                    => Result::Returned,
		'_e'                                     => Result::Printed,
		'_ex'                                    => Result::Printed,
		'esc_html__'                             => Result::Returned,
		'esc_html_x'                             => Result::Returned,
		'esc_html_e'                             => Result::Printed,
		'esc_attr__'                             => Result::Returned,
		'esc_attr_x'                             => Result::Returned,
		'esc_attr_e'                             => Result::Printed,
		'determine_locale'                       => Result::Returned,
		'get_user_locale'                        => Result::Returned,
		'wp_get_list_item_separator'             => Result::Returned,

		// Escaping and formatting: the escaping functions, text, dates and numbers.
		'esc_html'                               => Result::Returned,
		'esc_attr'                               => Result::Returned,
		'esc_url'                                => Result::Returned,
		'esc_url_raw'                            => Result::Returned,
		'esc_js'                                 => Result::Returned,
		'esc_textarea'                           => Result::Returned,
		'esc_xml'                                => Result::Returned,
		'tag_escape'                             => Result::Returned,
		'wp_kses'                                => Result::Returned,
		'wp_kses_post'                           => Result::Returned,
		'wp_kses_data'                           => Result::Returned,
		'wp_kses_one_attr'                       => Result::Returned,
		'wp_kses_allowed_html'                   => Result::Returned,
		'safecss_filter_attr'                    => Result::Returned,
		'sanitize_title'                         => Result::Returned,
		'sanitize_title_with_dashes'             => Result::Returned,
		'sanitize_html_class'                    => Result::Returned,
		'sanitize_key'                           => Result::Returned,
		'sanitize_text_field'                    => Result::Returned,
		'sanitize_textarea_field'                => Result::Returned,
		'sanitize_email'                         => Result::Returned,
		'sanitize_hex_color'                     => Result::Returned,
		'sanitize_hex_color_no_hash'             => Result::Returned,
		'wp_strip_all_tags'                      => Result::Returned,
		'wp_trim_words'                          => Result::Returned,
		'wp_html_excerpt'                        => Result::Returned,
		'wp_trim_excerpt'                        => Result::Returned,
		'excerpt_remove_blocks'                  => Result::Returned,
		'get_url_in_content'                     => Result::Returned,
		'wpautop'                                => Result::Returned,
		'shortcode_unautop'                      => Result::Returned,
		'force_balance_tags'                     => Result::Returned,
		'wptexturize'                            => Result::Returned,
		'convert_smilies'                        => Result::Returned,
		'wp_specialchars_decode'                 => Result::Returned,
		'remove_accents'                         => Result::Returned,
		'make_clickable'                         => Result::Returned,
		'wp_rel_nofollow'                        => Result::Returned,
		'wp_rel_ugc'                             => Result::Returned,
		'links_add_target'                       => Result::Returned,
		'url_shorten'                            => Result::Returned,
		'wp_make_link_relative'                  => Result::Returned,
		'trailingslashit'                        => Result::Returned,
		'untrailingslashit'                      => Result::Returned,
		'user_trailingslashit'                   => Result::Returned,
		'wp_basename'                            => Result::Returned,
		'antispambot'                            => Result::Returned,
		'wp_unique_id'                           => Result::Returned,
		'wp_unique_prefixed_id'                  => Result::Returned,
		'number_format_i18n'                     => Result::Returned,
		'wp_sprintf'                             => Result::Returned,
		'size_format'                            => Result::Returned,
		'human_time_diff'                        => Result::Returned,
		'human_readable_duration'                => Result::Returned,
		'date_i18n'                              => Result::Returned,
		'wp_date'                                => Result::Returned,
		'current_time'                           => Result::Returned,
		'current_datetime'                       => Result::Returned,
		'wp_timezone'                            => Result::Returned,
		'wp_timezone_string'                     => Result::Returned,
		'mysql2date'                             => Result::Returned,
		'mysql_to_rfc3339'                       => Result::Returned,
		'get_date_from_gmt'                      => Result::Returned,
		'get_gmt_from_date'                      => Result::Returned,

		// Hooks, shortcodes and blocks, the Interactivity API included.
		'do_action'                              => Result::Printed,
		'apply_filters'                          => Result::Returned,
		'did_action'                             => Result::Returned,
		'did_filter'                             => Result::Returned,
		'doing_action'                           => Result::Returned,
		'doing_filter'                           => Result::Returned,
		'has_action'                             => Result::Returned,
		'has_filter'                             => Result::Returned,
		'do_shortcode'                           => Result::Returned,
		'apply_shortcodes'                       => Result::Returned,
		'strip_shortcodes'                       => Result::Returned,
		'has_shortcode'                          => Result::Returned,
		'shortcode_exists'                       => Result::Returned,
		'do_blocks'                              => Result::Returned,
		'has_block'                              => Result::Returned,
		'has_blocks'                             => Result::Returned,
		'parse_blocks'                           => Result::Returned,
		'render_block'                           => Result::Returned,
		'serialize_block'                        => Result::Returned,
		'serialize_blocks'                       => Result::Returned,
		'get_block_wrapper_attributes'           => Result::Returned,
		'wp_interactivity_state'                 => Result::Returned,
		'wp_interactivity_config'                => Result::Returned,
		'wp_interactivity_data_wp_context'       => Result::Returned,
		'wp_interactivity_process_directives'    => Result::Returned,

		// Scripts and styles: what a template queues, and the script tags it prints.
		'wp_enqueue_script'                      => Result::Returned,
		'wp_enqueue_script_module'               => Result::Returned,
		'wp_enqueue_style'                       => Result::Returned,
		'wp_add_inline_script'                   => Result::Returned,
		'wp_add_inline_style'                    => Result::Returned,
		'wp_localize_script'                     => Result::Returned,
		'wp_script_is'                           => Result::Returned,
		'wp_style_is'                            => Result::Returned,
		'wp_print_script_tag'                    => Result::Printed,
		'wp_get_script_tag'                      => Result::Returned,
		'wp_print_inline_script_tag'             => Result::Printed,
		'wp_get_inline_script_tag'               => Result::Returned,

		// Addresses: of the site, of the theme, of the posts, of the archives and feeds, and around logging in.
		'home_url'                               => Result::Returned,
		'site_url'                               => Result::Returned,
		'get_home_url'                           => Result::Returned,
		'get_site_url'                           => Result::Returned,
		'network_home_url'                       => Result::Returned,
		'network_site_url'                       => Result::Returned,
		'set_url_scheme'                         => Result::Returned,
		'admin_url'                              => Result::Returned,
		'get_admin_url'                          => Result::Returned,
		'network_admin_url'                      => Result::Returned,
		'get_dashboard_url'                      => Result::Returned,
		'get_edit_profile_url'                   => Result::Returned,
		'get_edit_user_link'                     => Result::Returned,
		'get_delete_post_link'                   => Result::Returned,
		'rest_url'                               => Result::Returned,
		'get_rest_url'                           => Result::Returned,
		'includes_url'                           => Result::Returned,
		'content_url'                            => Result::Returned,
		'plugins_url'                            => Result::Returned,
		'wp_get_upload_dir'                      => Result::Returned,
		'get_theme_file_uri'                     => Result::Returned,
		'get_parent_theme_file_uri'              => Result::Returned,
		'get_template_directory_uri'             => Result::Returned,
		'get_stylesheet_directory_uri'           => Result::Returned,
		'get_stylesheet_uri'                     => Result::Returned,
		'get_privacy_policy_url'                 => Result::Returned,
		'get_the_privacy_policy_link'            => Result::Returned,
		'the_privacy_policy_link'                => Result::Printed,
		'get_search_link'                        => Result::Returned,
		'get_search_feed_link'                   => Result::Returned,
		'get_search_comments_feed_link'          => Result::Returned,
		'get_post_type_archive_link'             => Result::Returned,
		'get_post_type_archive_feed_link'        => Result::Returned,
		'get_author_posts_url'                   => Result::Returned,
		'get_author_feed_link'                   => Result::Returned,
		'get_page_link'                          => Result::Returned,
		'get_post_permalink'                     => Result::Returned,
		'get_attachment_link'                    => Result::Returned,
		'get_page_uri'                           => Result::Returned,
		'url_to_postid'                          => Result::Returned,
		'get_day_link'                           => Result::Returned,
		'get_month_link'                         => Result::Returned,
		'get_year_link'                          => Result::Returned,
		'get_feed_link'                          => Result::Returned,
		'the_feed_link'                          => Result::Printed,
		'post_comments_feed_link'                => Result::Printed,
		'get_post_comments_feed_link'            => Result::Returned,
		'get_category_feed_link'                 => Result::Returned,
		'get_tag_feed_link'                      => Result::Returned,
		'get_term_feed_link'                     => Result::Returned,
		'add_query_arg'                          => Result::Returned,
		'remove_query_arg'                       => Result::Returned,
		'wp_nonce_url'                           => Result::Returned,
		'the_shortlink'                          => Result::Printed,
		'wp_get_shortlink'                       => Result::Returned,
		'wp_get_canonical_url'                   => Result::Returned,
		'wp_get_referer'                         => Result::Returned,
		'wp_is_internal_link'                    => Result::Returned,
		'get_sitemap_url'                        => Result::Returned,

		// The query and the loop.
		'have_posts'                             => Result::Returned,
		'the_post'                               => Result::Returned,
		'rewind_posts'                           => Result::Returned,
		'in_the_loop'                            => Result::Returned,
		'setup_postdata'                         => Result::Returned,
		'wp_reset_postdata'                      => Result::Returned,
		'wp_reset_query'                         => Result::Returned,
		'is_main_query'                          => Result::Returned,
		'get_query_var'                          => Result::Returned,
		'get_queried_object'                     => Result::Returned,
		'get_queried_object_id'                  => Result::Returned,
		'get_post'                               => Result::Returned,
		'get_posts'                              => Result::Returned,
		'wp_get_recent_posts'                    => Result::Returned,
		'get_children'                           => Result::Returned,
		'wp_count_posts'                         => Result::Returned,
		'get_pages'                              => Result::Returned,
		'get_page_by_path'                       => Result::Returned,
		'get_post_field'                         => Result::Returned,
		'get_post_status'                        => Result::Returned,
		'get_post_mime_type'                     => Result::Returned,
		'get_extended'                           => Result::Returned,
		'get_post_meta'                          => Result::Returned,
		'metadata_exists'                        => Result::Returned,
		'get_post_custom'                        => Result::Returned,
		'get_post_custom_keys'                   => Result::Returned,
		'get_post_custom_values'                 => Result::Returned,
		'get_post_type'                          => Result::Returned,
		'get_post_type_object'                   => Result::Returned,
		'get_post_types'                         => Result::Returned,
		'post_type_supports'                     => Result::Returned,
		'get_post_format'                        => Result::Returned,
		'has_post_format'                        => Result::Returned,
		'get_post_format_string'                 => Result::Returned,
		'get_post_format_link'                   => Result::Returned,
		'get_post_format_strings'                => Result::Returned,
		'get_post_ancestors'                     => Result::Returned,
		'wp_get_post_parent_id'                  => Result::Returned,
		'get_post_parent'                        => Result::Returned,
		'has_post_parent'                        => Result::Returned,
		'get_previous_post'                      => Result::Returned,
		'get_next_post'                          => Result::Returned,
		'get_adjacent_post'                      => Result::Returned,
		'get_boundary_post'                      => Result::Returned,
		'get_lastpostdate'                       => Result::Returned,
		'get_lastpostmodified'                   => Result::Returned,

		// The post: its title, its address, its content, its dates and its author.
		'the_ID'                                 => Result::Printed,
		'get_the_ID'                             => Result::Returned,
		'the_guid'                               => Result::Printed,
		'get_the_guid'                           => Result::Returned,
		'the_title'                              => Result::Printed,
		'get_the_title'                          => Result::Returned,
		'the_title_attribute'                    => Result::Printed,
		'the_permalink'                          => Result::Printed,
		'get_permalink'                          => Result::Returned,
		'get_the_permalink'                      => Result::Returned,
		'the_content'                            => Result::Printed,
		'get_the_content'                        => Result::Returned,
		'the_excerpt'                            => Result::Printed,
		'get_the_excerpt'                        => Result::Returned,
		'has_excerpt'                            => Result::Returned,
		'post_class'                             => Result::Printed,
		'get_post_class'                         => Result::Returned,
		'the_date'                               => Result::Printed,
		'get_the_date'                           => Result::Returned,
		'the_time'                               => Result::Printed,
		'get_the_time'                           => Result::Returned,
		'the_modified_date'                      => Result::Printed,
		'get_the_modified_date'                  => Result::Returned,
		'the_modified_time'                      => Result::Printed,
		'get_the_modified_time'                  => Result::Returned,
		'get_post_time'                          => Result::Returned,
		'get_post_modified_time'                 => Result::Returned,
		'get_post_datetime'                      => Result::Returned,
		'get_post_timestamp'                     => Result::Returned,
		'the_author'                             => Result::Printed,
		'get_the_author'                         => Result::Returned,
		'the_modified_author'                    => Result::Printed,
		'get_the_modified_author'                => Result::Returned,
		'the_author_meta'                        => Result::Printed,
		'get_the_author_meta'                    => Result::Returned,
		'the_author_link'                        => Result::Printed,
		'get_the_author_link'                    => Result::Returned,
		'the_author_posts_link'                  => Result::Printed,
		'get_the_author_posts_link'              => Result::Returned,
		'the_author_posts'                       => Result::Printed,
		'get_the_author_posts'                   => Result::Returned,
		'is_sticky'                              => Result::Returned,
		'post_password_required'                 => Result::Returned,
		'get_the_password_form'                  => Result::Returned,
		'wp_link_pages'                          => Result::Printed,
		'edit_post_link'                         => Result::Printed,
		'get_edit_post_link'                     => Result::Returned,
		'get_page_template_slug'                 => Result::Returned,

		// The featured image, the media library, and the galleries, players and embeds.
		'has_post_thumbnail'                     => Result::Returned,
		'get_post_thumbnail_id'                  => Result::Returned,
		'the_post_thumbnail'                     => Result::Printed,
		'get_the_post_thumbnail'                 => Result::Returned,
		'the_post_thumbnail_url'                 => Result::Printed,
		'get_the_post_thumbnail_url'             => Result::Returned,
		'the_post_thumbnail_caption'             => Result::Printed,
		'get_the_post_thumbnail_caption'         => Result::Returned,
		'wp_get_attachment_image'                => Result::Returned,
		'wp_get_attachment_image_src'            => Result::Returned,
		'wp_get_attachment_image_url'            => Result::Returned,
		'wp_get_attachment_thumb_url'            => Result::Returned,
		'wp_get_original_image_url'              => Result::Returned,
		'wp_get_attachment_image_srcset'         => Result::Returned,
		'wp_get_attachment_image_sizes'          => Result::Returned,
		'wp_get_loading_optimization_attributes' => Result::Returned,
		'wp_filter_content_tags'                 => Result::Returned,
		'wp_get_attachment_url'                  => Result::Returned,
		'attachment_url_to_postid'               => Result::Returned,
		'wp_get_attachment_caption'              => Result::Returned,
		'wp_get_attachment_metadata'             => Result::Returned,
		'wp_get_attachment_link'                 => Result::Returned,
		'the_attachment_link'                    => Result::Printed,
		'wp_attachment_is_image'                 => Result::Returned,
		'wp_attachment_is'                       => Result::Returned,
		'wp_mime_type_icon'                      => Result::Returned,
		'get_attached_media'                     => Result::Returned,
		'get_media_embedded_in_content'          => Result::Returned,
		'get_post_gallery'                       => Result::Returned,
		'get_post_galleries'                     => Result::Returned,
		'get_post_gallery_images'                => Result::Returned,
		'get_post_galleries_images'              => Result::Returned,
		'previous_image_link'                    => Result::Printed,
		'get_previous_image_link'                => Result::Returned,
		'next_image_link'                        => Result::Printed,
		'get_next_image_link'                    => Result::Returned,
		'adjacent_image_link'                    => Result::Printed,
		'get_adjacent_image_link'                => Result::Returned,
		'gallery_shortcode'                      => Result::Returned,
		'img_caption_shortcode'                  => Result::Returned,
		'wp_audio_shortcode'                     => Result::Returned,
		'wp_video_shortcode'                     => Result::Returned,
		'wp_playlist_shortcode'                  => Result::Returned,
		'wp_oembed_get'                          => Result::Returned,
		'get_post_embed_html'                    => Result::Returned,
		'get_post_embed_url'                     => Result::Returned,

		// Categories, tags, the terms of any taxonomy, and the taxonomies themselves.
		'the_category'                           => Result::Printed,
		'get_the_category'                       => Result::Returned,
		'get_the_category_list'                  => Result::Returned,
		'get_the_category_by_ID'                 => Result::Returned,
		'get_category_parents'                   => Result::Returned,
		'the_tags'                               => Result::Printed,
		'get_the_tags'                           => Result::Returned,
		'get_the_tag_list'                       => Result::Returned,
		'the_terms'                              => Result::Printed,
		'get_the_terms'                          => Result::Returned,
		'get_the_term_list'                      => Result::Returned,
		'get_term_parents_list'                  => Result::Returned,
		'the_taxonomies'                         => Result::Printed,
		'get_the_taxonomies'                     => Result::Returned,
		'wp_get_post_terms'                      => Result::Returned,
		'wp_get_post_categories'                 => Result::Returned,
		'wp_get_post_tags'                       => Result::Returned,
		'wp_get_object_terms'                    => Result::Returned,
		'has_category'                           => Result::Returned,
		'has_tag'                                => Result::Returned,
		'has_term'                               => Result::Returned,
		'is_object_in_term'                      => Result::Returned,
		'is_object_in_taxonomy'                  => Result::Returned,
		'in_category'                            => Result::Returned,
		'cat_is_ancestor_of'                     => Result::Returned,
		'term_is_ancestor_of'                    => Result::Returned,
		'term_exists'                            => Result::Returned,
		'get_term'                               => Result::Returned,
		'get_terms'                              => Result::Returned,
		'get_term_by'                            => Result::Returned,
		'get_term_field'                         => Result::Returned,
		'get_term_children'                      => Result::Returned,
		'get_ancestors'                          => Result::Returned,
		'wp_count_terms'                         => Result::Returned,
		'get_categories'                         => Result::Returned,
		'get_category'                           => Result::Returned,
		'get_category_by_slug'                   => Result::Returned,
		'get_cat_name'                           => Result::Returned,
		'get_cat_ID'                             => Result::Returned,
		'get_tags'                               => Result::Returned,
		'get_tag'                                => Result::Returned,
		'get_term_link'                          => Result::Returned,
		'get_category_link'                      => Result::Returned,
		'get_tag_link'                           => Result::Returned,
		'get_term_meta'                          => Result::Returned,
		'get_taxonomies'                         => Result::Returned,
		'get_taxonomy'                           => Result::Returned,
		'get_object_taxonomies'                  => Result::Returned,
		'get_post_taxonomies'                    => Result::Returned,
		'single_cat_title'                       => Result::Printed,
		'single_tag_title'                       => Result::Printed,
		'single_term_title'                      => Result::Printed,
		'term_description'                       => Result::Returned,
		'category_description'                   => Result::Returned,
		'tag_description'                        => Result::Returned,
		'wp_list_categories'                     => Result::Printed,
		'wp_dropdown_categories'                 => Result::Printed,
		'wp_tag_cloud'                           => Result::Printed,
		'wp_generate_tag_cloud'                  => Result::Returned,
		'edit_term_link'                         => Result::Printed,
		'get_edit_term_link'                     => Result::Returned,
		'edit_tag_link'                          => Result::Printed,
		'get_edit_tag_link'                      => Result::Returned,

		// Archives and pagination: the title of an archive, and the links between its pages and between posts.
		'the_archive_title'                      => Result::Printed,
		'get_the_archive_title'                  => Result::Returned,
		'the_archive_description'                => Result::Printed,
		'get_the_archive_description'            => Result::Returned,
		'get_the_post_type_description'          => Result::Returned,
		'single_post_title'                      => Result::Printed,
		'post_type_archive_title'                => Result::Printed,
		'single_month_title'                     => Result::Printed,
		'wp_get_archives'                        => Result::Printed,
		'get_archives_link'                      => Result::Returned,
		'get_calendar'                           => Result::Printed,
		'the_posts_pagination'                   => Result::Printed,
		'get_the_posts_pagination'               => Result::Returned,
		'the_posts_navigation'                   => Result::Printed,
		'get_the_posts_navigation'               => Result::Returned,
		'paginate_links'                         => Result::Returned,
		'posts_nav_link'                         => Result::Printed,
		'get_posts_nav_link'                     => Result::Returned,
		'next_posts_link'                        => Result::Printed,
		'previous_posts_link'                    => Result::Printed,
		'get_next_posts_link'                    => Result::Returned,
		'get_previous_posts_link'                => Result::Returned,
		'next_posts'                             => Result::Printed,
		'get_next_posts_page_link'               => Result::Returned,
		'previous_posts'                         => Result::Printed,
		'get_previous_posts_page_link'           => Result::Returned,
		'get_pagenum_link'                       => Result::Returned,
		'the_post_navigation'                    => Result::Printed,
		'get_the_post_navigation'                => Result::Returned,
		'next_post_link'                         => Result::Printed,
		'previous_post_link'                     => Result::Printed,
		'get_next_post_link'                     => Result::Returned,
		'get_previous_post_link'                 => Result::Returned,
		'adjacent_post_link'                     => Result::Printed,
		'get_adjacent_post_link'                 => Result::Returned,

		// Menus, and the lists of pages and of links.
		'wp_nav_menu'                            => Result::Printed,
		'has_nav_menu'                           => Result::Returned,
		'wp_get_nav_menu_items'                  => Result::Returned,
		'wp_get_nav_menu_object'                 => Result::Returned,
		'wp_get_nav_menus'                       => Result::Returned,
		'is_nav_menu'                            => Result::Returned,
		'get_nav_menu_locations'                 => Result::Returned,
		'get_registered_nav_menus'               => Result::Returned,
		'wp_get_nav_menu_name'                   => Result::Returned,
		'wp_list_pages'                          => Result::Printed,
		'wp_page_menu'                           => Result::Printed,
		'wp_dropdown_pages'                      => Result::Printed,
		'wp_list_bookmarks'                      => Result::Printed,
		'get_bookmarks'                          => Result::Returned,
		'get_bookmark'                           => Result::Returned,

		// Sidebars, template parts, header.php and footer.php included, and the search.
		'dynamic_sidebar'                        => Result::Printed,
		'is_active_sidebar'                      => Result::Returned,
		'is_dynamic_sidebar'                     => Result::Returned,
		'is_registered_sidebar'                  => Result::Returned,
		'wp_get_sidebar'                         => Result::Returned,
		'the_widget'                             => Result::Printed,
		'is_active_widget'                       => Result::Returned,
		'wp_meta'                                => Result::Printed,
		'get_header'                             => Result::Printed,
		'get_footer'                             => Result::Printed,
		'get_sidebar'                            => Result::Printed,
		'get_template_part'                      => Result::Printed,
		'block_template_part'                    => Result::Printed,
		'block_header_area'                      => Result::Printed,
		'block_footer_area'                      => Result::Printed,
		'get_search_form'                        => Result::Printed,
		'get_search_query'                       => Result::Returned,
		'the_search_query'                       => Result::Printed,

		// Comments.
		'comments_open'                          => Result::Returned,
		'pings_open'                             => Result::Returned,
		'have_comments'                          => Result::Returned,
		'the_comment'                            => Result::Returned,
		'comments_template'                      => Result::Printed,
		'get_comments'                           => Result::Returned,
		'get_comment'                            => Result::Returned,
		'get_approved_comments'                  => Result::Returned,
		'get_comment_count'                      => Result::Returned,
		'wp_count_comments'                      => Result::Returned,
		'get_comment_meta'                       => Result::Returned,
		'wp_get_comment_status'                  => Result::Returned,
		'get_comments_number'                    => Result::Returned,
		'comments_number'                        => Result::Printed,
		'get_comments_number_text'               => Result::Returned,
		'get_comments_link'                      => Result::Returned,
		'comments_link'                          => Result::Printed,
		'get_comment_link'                       => Result::Returned,
		'get_page_of_comment'                    => Result::Returned,
		'wp_list_comments'                       => Result::Printed,
		'comment_form'                           => Result::Printed,
		'comment_form_title'                     => Result::Printed,
		'comment_id_fields'                      => Result::Printed,
		'get_comment_id_fields'                  => Result::Returned,
		'wp_get_current_commenter'               => Result::Returned,
		'wp_get_unapproved_comment_author_email' => Result::Returned,
		'comment_class'                          => Result::Printed,
		'get_comment_class'                      => Result::Returned,
		'comment_ID'                             => Result::Printed,
		'get_comment_ID'                         => Result::Returned,
		'comment_author'                         => Result::Printed,
		'get_comment_author'                     => Result::Returned,
		'comment_author_link'                    => Result::Printed,
		'get_comment_author_link'                => Result::Returned,
		'comment_author_email'                   => Result::Printed,
		'get_comment_author_email'               => Result::Returned,
		'comment_author_email_link'              => Result::Printed,
		'get_comment_author_email_link'          => Result::Returned,
		'comment_author_url'                     => Result::Printed,
		'get_comment_author_url'                 => Result::Returned,
		'comment_author_url_link'                => Result::Printed,
		'get_comment_author_url_link'            => Result::Returned,
		'comment_text'                           => Result::Printed,
		'get_comment_text'                       => Result::Returned,
		'comment_excerpt'                        => Result::Printed,
		'get_comment_excerpt'                    => Result::Returned,
		'comment_date'                           => Result::Printed,
		'get_comment_date'                       => Result::Returned,
		'comment_time'                           => Result::Printed,
		'get_comment_time'                       => Result::Returned,
		'comment_type'                           => Result::Printed,
		'get_comment_type'                       => Result::Returned,
		'comment_reply_link'                     => Result::Printed,
		'get_comment_reply_link'                 => Result::Returned,
		'post_reply_link'                        => Result::Printed,
		'get_post_reply_link'                    => Result::Returned,
		'cancel_comment_reply_link'              => Result::Printed,
		'get_cancel_comment_reply_link'          => Result::Returned,
		'comments_popup_link'                    => Result::Printed,
		'edit_comment_link'                      => Result::Printed,
		'get_edit_comment_link'                  => Result::Returned,
		'the_comments_navigation'                => Result::Printed,
		'get_the_comments_navigation'            => Result::Returned,
		'the_comments_pagination'                => Result::Printed,
		'get_the_comments_pagination'            => Result::Returned,
		'get_comment_pages_count'                => Result::Returned,
		'paginate_comments_links'                => Result::Printed,
		'get_comments_pagenum_link'              => Result::Returned,
		'previous_comments_link'                 => Result::Printed,
		'next_comments_link'                     => Result::Printed,
		'get_previous_comments_link'             => Result::Returned,
		'get_next_comments_link'                 => Result::Returned,
		'trackback_url'                          => Result::Printed,
		'get_trackback_url'                      => Result::Returned,

		// Users, logging in, and forms.
		'is_user_logged_in'                      => Result::Returned,
		'current_user_can'                       => Result::Returned,
		'user_can'                               => Result::Returned,
		'author_can'                             => Result::Returned,
		'get_current_user_id'                    => Result::Returned,
		'wp_get_current_user'                    => Result::Returned,
		'get_userdata'                           => Result::Returned,
		'get_user_by'                            => Result::Returned,
		'get_user_meta'                          => Result::Returned,
		'get_users'                              => Result::Returned,
		'count_user_posts'                       => Result::Returned,
		'count_many_users_posts'                 => Result::Returned,
		'is_super_admin'                         => Result::Returned,
		'is_multi_author'                        => Result::Returned,
		'wp_list_authors'                        => Result::Printed,
		'wp_list_users'                          => Result::Printed,
		'wp_dropdown_users'                      => Result::Printed,
		'get_avatar'                             => Result::Returned,
		'get_avatar_url'                         => Result::Returned,
		'get_avatar_data'                        => Result::Returned,
		'wp_loginout'                            => Result::Printed,
		'wp_register'                            => Result::Printed,
		'wp_login_form'                          => Result::Printed,
		'wp_login_url'                           => Result::Returned,
		'wp_logout_url'                          => Result::Returned,
		'wp_registration_url'                    => Result::Returned,
		'wp_lostpassword_url'                    => Result::Returned,
		'wp_nonce_field'                         => Result::Printed,
		'wp_create_nonce'                        => Result::Returned,
		'wp_referer_field'                       => Result::Printed,
		'wp_original_referer_field'              => Result::Printed,
		'selected'                               => Result::Printed,
		'checked'                                => Result::Printed,
		'disabled'                               => Result::Printed,
		'wp_readonly'                            => Result::Printed,
		'wp_required_field_indicator'            => Result::Returned,
		'wp_required_field_message'              => Result::Returned,

		// Conditional tags.
		'is_home'                                => Result::Returned,
		'is_front_page'                          => Result::Returned,
		'is_single'                              => Result::Returned,
		'is_singular'                            => Result::Returned,
		'is_page'                                => Result::Returned,
		'is_page_template'                       => Result::Returned,
		'is_category'                            => Result::Returned,
		'is_tag'                                 => Result::Returned,
		'is_tax'                                 => Result::Returned,
		'is_author'                              => Result::Returned,
		'is_date'                                => Result::Returned,
		'is_year'                                => Result::Returned,
		'is_month'                               => Result::Returned,
		'is_day'                                 => Result::Returned,
		'is_time'                                => Result::Returned,
		'is_archive'                             => Result::Returned,
		'is_search'                              => Result::Returned,
		'is_404'                                 => Result::Returned,
		'is_attachment'                          => Result::Returned,
		'is_post_type_archive'                   => Result::Returned,
		'is_privacy_policy'                      => Result::Returned,
		'is_paged'                               => Result::Returned,
		'is_preview'                             => Result::Returned,
		'is_feed'                                => Result::Returned,
		'is_comment_feed'                        => Result::Returned,
		'is_trackback'                           => Result::Returned,
		'is_embed'                               => Result::Returned,
		'is_robots'                              => Result::Returned,
		'is_favicon'                             => Result::Returned,
		'is_new_day'                             => Result::Returned,
		'is_admin'                               => Result::Returned,
		'is_login'                               => Result::Returned,
		'is_admin_bar_showing'                   => Result::Returned,
		'wp_doing_ajax'                          => Result::Returned,
		'is_customize_preview'                   => Result::Returned,
		'is_multisite'                           => Result::Returned,
		'is_main_site'                           => Result::Returned,
		'is_child_theme'                         => Result::Returned,
		'wp_is_block_theme'                      => Result::Returned,
		'wp_theme_has_theme_json'                => Result::Returned,
		'is_ssl'                                 => Result::Returned,
		'wp_is_mobile'                           => Result::Returned,
		'current_theme_supports'                 => Result::Returned,
		'post_type_exists'                       => Result::Returned,
		'taxonomy_exists'                        => Result::Returned,
		'is_post_type_hierarchical'              => Result::Returned,
		'is_post_type_viewable'                  => Result::Returned,
		'is_post_status_viewable'                => Result::Returned,
		'is_post_publicly_viewable'              => Result::Returned,
		'is_taxonomy_hierarchical'               => Result::Returned,
		'is_taxonomy_viewable'                   => Result::Returned,
		'is_term_publicly_viewable'              => Result::Returned,
		'is_wp_error'                            => Result::Returned,

		// Settings and environment.
		'get_option'                             => Result::Returned,
		'get_site_option'                        => Result::Returned,
		'get_theme_mod'                          => Result::Returned,
		'get_theme_mods'                         => Result::Returned,
		'get_theme_support'                      => Result::Returned,
		'wp_get_theme'                           => Result::Returned,
		'get_template'                           => Result::Returned,
		'get_stylesheet'                         => Result::Returned,
		'get_template_directory'                 => Result::Returned,
		'get_stylesheet_directory'               => Result::Returned,
		'get_theme_file_path'                    => Result::Returned,
		'get_parent_theme_file_path'             => Result::Returned,
		'wp_get_global_settings'                 => Result::Returned,
		'wp_get_global_styles'                   => Result::Returned,
		'wp_get_global_stylesheet'               => Result::Returned,
		'wp_get_environment_type'                => Result::Returned,
		'wp_get_development_mode'                => Result::Returned,
		'wp_is_development_mode'                 => Result::Returned,
		'get_current_blog_id'                    => Result::Returned,
	);
}
