<?php
/**
 * OffsetWP Twig WordPress Extension
 *
 * @author Jérôme Wohlschlegel
 * @package OffsetWP\Twig\Extension\WordPressExtension
 */

declare( strict_types=1 );

namespace OffsetWP\Twig\Extension\WordPressExtension;

/**
 * The functions of WordPress a template can call by their name, and where each one puts its
 * result.
 *
 * The list is the one a theme needs, and no wider. It starts from the functions the
 * starter theme of OffsetWP calls, adds the template tags and the conditional tags the
 * handbook of WordPress lists, and the functions the classic default themes call in their
 * templates. Left out on purpose are the functions that load a PHP file a Twig theme does
 * not have — get_header(), get_footer(), get_sidebar() —, those that only work before the
 * head is printed, those that live in wp-admin, and the deprecated ones. fn() reaches every
 * one of them all the same.
 *
 * Whether a function prints or returns was read in the source of WordPress, function by
 * function, and not guessed from its name. A function that echoes, includes a file, fires
 * an action or hands its work to a helper that echoes is Result::Printed. One that only
 * computes its result and hands it back is Result::Returned, even when an action it fires on
 * the way could print — the_post() is one, and so is get_the_post_thumbnail(). Every
 * function exists since WordPress 6.5, which the test suite proves against the stubs of
 * that version, and takes no argument by reference, which Twig could not pass.
 *
 * The groups are the ones the README lists the functions in, in the same order. A function
 * added here is added there as well, which a test asserts.
 */
final class Catalogue {

	/**
	 * Every function, by name, with where it puts its result.
	 *
	 * @var array<string, Result>
	 */
	public const FUNCTIONS = array(
		// The document: its head, its body, and what the site is called and looks like.
		'wp_head'                        => Result::Printed,
		'wp_footer'                      => Result::Printed,
		'wp_body_open'                   => Result::Printed,
		'language_attributes'            => Result::Printed,
		'get_language_attributes'        => Result::Returned,
		'body_class'                     => Result::Printed,
		'get_body_class'                 => Result::Returned,
		'bloginfo'                       => Result::Printed,
		'get_bloginfo'                   => Result::Returned,
		'wp_get_document_title'          => Result::Returned,
		'get_locale'                     => Result::Returned,
		'is_rtl'                         => Result::Returned,
		'site_icon_url'                  => Result::Printed,
		'get_site_icon_url'              => Result::Returned,
		'has_site_icon'                  => Result::Returned,
		'the_custom_logo'                => Result::Printed,
		'get_custom_logo'                => Result::Returned,
		'has_custom_logo'                => Result::Returned,
		'header_image'                   => Result::Printed,
		'get_header_image'               => Result::Returned,
		'has_header_image'               => Result::Returned,
		'the_custom_header_markup'       => Result::Printed,
		'get_custom_header_markup'       => Result::Returned,
		'display_header_text'            => Result::Returned,
		'get_header_textcolor'           => Result::Returned,
		'get_background_image'           => Result::Returned,
		'get_background_color'           => Result::Returned,

		// Translation: the gettext functions, those that print and those that escape.
		'__'                             => Result::Returned,
		'_x'                             => Result::Returned,
		'_n'                             => Result::Returned,
		'_nx'                            => Result::Returned,
		'_e'                             => Result::Printed,
		'_ex'                            => Result::Printed,
		'esc_html__'                     => Result::Returned,
		'esc_html_x'                     => Result::Returned,
		'esc_html_e'                     => Result::Printed,
		'esc_attr__'                     => Result::Returned,
		'esc_attr_x'                     => Result::Returned,
		'esc_attr_e'                     => Result::Printed,

		// Escaping and formatting: the escaping functions, text, dates and numbers.
		'esc_html'                       => Result::Returned,
		'esc_attr'                       => Result::Returned,
		'esc_url'                        => Result::Returned,
		'esc_js'                         => Result::Returned,
		'esc_textarea'                   => Result::Returned,
		'esc_xml'                        => Result::Returned,
		'wp_kses'                        => Result::Returned,
		'wp_kses_post'                   => Result::Returned,
		'wp_kses_data'                   => Result::Returned,
		'sanitize_title'                 => Result::Returned,
		'sanitize_html_class'            => Result::Returned,
		'wp_strip_all_tags'              => Result::Returned,
		'wp_trim_words'                  => Result::Returned,
		'wp_html_excerpt'                => Result::Returned,
		'wpautop'                        => Result::Returned,
		'wptexturize'                    => Result::Returned,
		'make_clickable'                 => Result::Returned,
		'antispambot'                    => Result::Returned,
		'wp_unique_id'                   => Result::Returned,
		'number_format_i18n'             => Result::Returned,
		'size_format'                    => Result::Returned,
		'human_time_diff'                => Result::Returned,
		'date_i18n'                      => Result::Returned,
		'wp_date'                        => Result::Returned,
		'current_time'                   => Result::Returned,

		// Hooks, shortcodes and blocks.
		'do_action'                      => Result::Printed,
		'apply_filters'                  => Result::Returned,
		'do_shortcode'                   => Result::Returned,
		'strip_shortcodes'               => Result::Returned,
		'has_shortcode'                  => Result::Returned,
		'shortcode_exists'               => Result::Returned,
		'do_blocks'                      => Result::Returned,
		'has_block'                      => Result::Returned,
		'has_blocks'                     => Result::Returned,

		// Addresses: of the site, of the theme, of the archives, and around logging in.
		'home_url'                       => Result::Returned,
		'site_url'                       => Result::Returned,
		'get_home_url'                   => Result::Returned,
		'get_site_url'                   => Result::Returned,
		'admin_url'                      => Result::Returned,
		'rest_url'                       => Result::Returned,
		'get_theme_file_uri'             => Result::Returned,
		'get_parent_theme_file_uri'      => Result::Returned,
		'get_template_directory_uri'     => Result::Returned,
		'get_stylesheet_directory_uri'   => Result::Returned,
		'get_stylesheet_uri'             => Result::Returned,
		'get_privacy_policy_url'         => Result::Returned,
		'get_the_privacy_policy_link'    => Result::Returned,
		'the_privacy_policy_link'        => Result::Printed,
		'get_search_link'                => Result::Returned,
		'get_post_type_archive_link'     => Result::Returned,
		'get_author_posts_url'           => Result::Returned,
		'get_day_link'                   => Result::Returned,
		'get_month_link'                 => Result::Returned,
		'get_year_link'                  => Result::Returned,
		'get_feed_link'                  => Result::Returned,
		'add_query_arg'                  => Result::Returned,
		'remove_query_arg'               => Result::Returned,
		'wp_nonce_url'                   => Result::Returned,

		// The query and the loop.
		'have_posts'                     => Result::Returned,
		'the_post'                       => Result::Returned,
		'rewind_posts'                   => Result::Returned,
		'in_the_loop'                    => Result::Returned,
		'setup_postdata'                 => Result::Returned,
		'wp_reset_postdata'              => Result::Returned,
		'wp_reset_query'                 => Result::Returned,
		'is_main_query'                  => Result::Returned,
		'get_query_var'                  => Result::Returned,
		'get_queried_object'             => Result::Returned,
		'get_queried_object_id'          => Result::Returned,
		'get_post'                       => Result::Returned,
		'get_posts'                      => Result::Returned,
		'get_pages'                      => Result::Returned,
		'get_page_by_path'               => Result::Returned,
		'get_post_field'                 => Result::Returned,
		'get_post_meta'                  => Result::Returned,
		'get_post_type'                  => Result::Returned,
		'get_post_type_object'           => Result::Returned,
		'get_post_format'                => Result::Returned,
		'has_post_format'                => Result::Returned,
		'get_post_ancestors'             => Result::Returned,
		'wp_get_post_parent_id'          => Result::Returned,
		'get_previous_post'              => Result::Returned,
		'get_next_post'                  => Result::Returned,

		// The post: its title, its address, its content, its dates and its author.
		'the_ID'                         => Result::Printed,
		'get_the_ID'                     => Result::Returned,
		'the_title'                      => Result::Printed,
		'get_the_title'                  => Result::Returned,
		'the_title_attribute'            => Result::Printed,
		'the_permalink'                  => Result::Printed,
		'get_permalink'                  => Result::Returned,
		'get_the_permalink'              => Result::Returned,
		'the_content'                    => Result::Printed,
		'get_the_content'                => Result::Returned,
		'the_excerpt'                    => Result::Printed,
		'get_the_excerpt'                => Result::Returned,
		'has_excerpt'                    => Result::Returned,
		'post_class'                     => Result::Printed,
		'get_post_class'                 => Result::Returned,
		'the_date'                       => Result::Printed,
		'get_the_date'                   => Result::Returned,
		'the_time'                       => Result::Printed,
		'get_the_time'                   => Result::Returned,
		'the_modified_date'              => Result::Printed,
		'get_the_modified_date'          => Result::Returned,
		'the_modified_time'              => Result::Printed,
		'get_the_modified_time'          => Result::Returned,
		'get_post_time'                  => Result::Returned,
		'get_post_modified_time'         => Result::Returned,
		'the_author'                     => Result::Printed,
		'get_the_author'                 => Result::Returned,
		'the_author_meta'                => Result::Printed,
		'get_the_author_meta'            => Result::Returned,
		'the_author_link'                => Result::Printed,
		'get_the_author_link'            => Result::Returned,
		'the_author_posts_link'          => Result::Printed,
		'get_the_author_posts_link'      => Result::Returned,
		'is_sticky'                      => Result::Returned,
		'post_password_required'         => Result::Returned,
		'get_the_password_form'          => Result::Returned,
		'wp_link_pages'                  => Result::Printed,
		'edit_post_link'                 => Result::Printed,
		'get_edit_post_link'             => Result::Returned,
		'get_page_template_slug'         => Result::Returned,

		// The featured image and the media library.
		'has_post_thumbnail'             => Result::Returned,
		'get_post_thumbnail_id'          => Result::Returned,
		'the_post_thumbnail'             => Result::Printed,
		'get_the_post_thumbnail'         => Result::Returned,
		'the_post_thumbnail_url'         => Result::Printed,
		'get_the_post_thumbnail_url'     => Result::Returned,
		'the_post_thumbnail_caption'     => Result::Printed,
		'get_the_post_thumbnail_caption' => Result::Returned,
		'wp_get_attachment_image'        => Result::Returned,
		'wp_get_attachment_image_src'    => Result::Returned,
		'wp_get_attachment_image_url'    => Result::Returned,
		'wp_get_attachment_image_srcset' => Result::Returned,
		'wp_get_attachment_image_sizes'  => Result::Returned,
		'wp_get_attachment_url'          => Result::Returned,
		'wp_get_attachment_caption'      => Result::Returned,
		'wp_get_attachment_metadata'     => Result::Returned,
		'wp_get_attachment_link'         => Result::Returned,
		'wp_attachment_is_image'         => Result::Returned,
		'wp_oembed_get'                  => Result::Returned,

		// Categories, tags and the terms of any taxonomy.
		'the_category'                   => Result::Printed,
		'get_the_category'               => Result::Returned,
		'get_the_category_list'          => Result::Returned,
		'the_tags'                       => Result::Printed,
		'get_the_tags'                   => Result::Returned,
		'get_the_tag_list'               => Result::Returned,
		'the_terms'                      => Result::Printed,
		'get_the_terms'                  => Result::Returned,
		'get_the_term_list'              => Result::Returned,
		'wp_get_post_terms'              => Result::Returned,
		'has_category'                   => Result::Returned,
		'has_tag'                        => Result::Returned,
		'has_term'                       => Result::Returned,
		'in_category'                    => Result::Returned,
		'get_term'                       => Result::Returned,
		'get_terms'                      => Result::Returned,
		'get_term_by'                    => Result::Returned,
		'get_categories'                 => Result::Returned,
		'get_tags'                       => Result::Returned,
		'get_term_link'                  => Result::Returned,
		'get_category_link'              => Result::Returned,
		'get_tag_link'                   => Result::Returned,
		'get_term_meta'                  => Result::Returned,
		'single_cat_title'               => Result::Printed,
		'single_tag_title'               => Result::Printed,
		'single_term_title'              => Result::Printed,
		'term_description'               => Result::Returned,
		'category_description'           => Result::Returned,
		'tag_description'                => Result::Returned,
		'wp_list_categories'             => Result::Printed,
		'wp_dropdown_categories'         => Result::Printed,
		'wp_tag_cloud'                   => Result::Printed,
		'edit_term_link'                 => Result::Printed,

		// Archives and pagination: the title of an archive, and the links between its pages and between posts.
		'the_archive_title'              => Result::Printed,
		'get_the_archive_title'          => Result::Returned,
		'the_archive_description'        => Result::Printed,
		'get_the_archive_description'    => Result::Returned,
		'single_post_title'              => Result::Printed,
		'post_type_archive_title'        => Result::Printed,
		'single_month_title'             => Result::Printed,
		'wp_get_archives'                => Result::Printed,
		'get_calendar'                   => Result::Printed,
		'the_posts_pagination'           => Result::Printed,
		'get_the_posts_pagination'       => Result::Returned,
		'the_posts_navigation'           => Result::Printed,
		'get_the_posts_navigation'       => Result::Returned,
		'paginate_links'                 => Result::Returned,
		'posts_nav_link'                 => Result::Printed,
		'next_posts_link'                => Result::Printed,
		'previous_posts_link'            => Result::Printed,
		'get_next_posts_link'            => Result::Returned,
		'get_previous_posts_link'        => Result::Returned,
		'the_post_navigation'            => Result::Printed,
		'get_the_post_navigation'        => Result::Returned,
		'next_post_link'                 => Result::Printed,
		'previous_post_link'             => Result::Printed,
		'get_next_post_link'             => Result::Returned,
		'get_previous_post_link'         => Result::Returned,

		// Menus.
		'wp_nav_menu'                    => Result::Printed,
		'has_nav_menu'                   => Result::Returned,
		'wp_get_nav_menu_items'          => Result::Returned,
		'wp_get_nav_menu_object'         => Result::Returned,
		'get_nav_menu_locations'         => Result::Returned,
		'wp_get_nav_menu_name'           => Result::Returned,
		'wp_list_pages'                  => Result::Printed,
		'wp_page_menu'                   => Result::Printed,

		// Sidebars, template parts and the search.
		'dynamic_sidebar'                => Result::Printed,
		'is_active_sidebar'              => Result::Returned,
		'the_widget'                     => Result::Printed,
		'get_template_part'              => Result::Printed,
		'get_search_form'                => Result::Printed,
		'get_search_query'               => Result::Returned,
		'the_search_query'               => Result::Printed,

		// Comments.
		'comments_open'                  => Result::Returned,
		'pings_open'                     => Result::Returned,
		'have_comments'                  => Result::Returned,
		'comments_template'              => Result::Printed,
		'get_comments'                   => Result::Returned,
		'get_comments_number'            => Result::Returned,
		'comments_number'                => Result::Printed,
		'get_comments_number_text'       => Result::Returned,
		'get_comments_link'              => Result::Returned,
		'get_comment_link'               => Result::Returned,
		'wp_list_comments'               => Result::Printed,
		'comment_form'                   => Result::Printed,
		'comment_class'                  => Result::Printed,
		'get_comment_class'              => Result::Returned,
		'comment_author'                 => Result::Printed,
		'get_comment_author'             => Result::Returned,
		'comment_author_link'            => Result::Printed,
		'get_comment_author_link'        => Result::Returned,
		'comment_text'                   => Result::Printed,
		'get_comment_text'               => Result::Returned,
		'comment_date'                   => Result::Printed,
		'get_comment_date'               => Result::Returned,
		'comment_time'                   => Result::Printed,
		'get_comment_time'               => Result::Returned,
		'comment_reply_link'             => Result::Printed,
		'get_comment_reply_link'         => Result::Returned,
		'cancel_comment_reply_link'      => Result::Printed,
		'comments_popup_link'            => Result::Printed,
		'edit_comment_link'              => Result::Printed,
		'get_edit_comment_link'          => Result::Returned,
		'the_comments_navigation'        => Result::Printed,
		'get_the_comments_navigation'    => Result::Returned,
		'the_comments_pagination'        => Result::Printed,
		'get_the_comments_pagination'    => Result::Returned,
		'paginate_comments_links'        => Result::Printed,
		'previous_comments_link'         => Result::Printed,
		'next_comments_link'             => Result::Printed,

		// Users, logging in, and forms.
		'is_user_logged_in'              => Result::Returned,
		'current_user_can'               => Result::Returned,
		'get_current_user_id'            => Result::Returned,
		'wp_get_current_user'            => Result::Returned,
		'get_userdata'                   => Result::Returned,
		'get_user_by'                    => Result::Returned,
		'get_user_meta'                  => Result::Returned,
		'is_super_admin'                 => Result::Returned,
		'is_multi_author'                => Result::Returned,
		'get_avatar'                     => Result::Returned,
		'get_avatar_url'                 => Result::Returned,
		'wp_loginout'                    => Result::Printed,
		'wp_register'                    => Result::Printed,
		'wp_login_form'                  => Result::Printed,
		'wp_login_url'                   => Result::Returned,
		'wp_logout_url'                  => Result::Returned,
		'wp_registration_url'            => Result::Returned,
		'wp_lostpassword_url'            => Result::Returned,
		'wp_nonce_field'                 => Result::Printed,
		'wp_create_nonce'                => Result::Returned,
		'selected'                       => Result::Printed,
		'checked'                        => Result::Printed,
		'disabled'                       => Result::Printed,

		// Conditional tags.
		'is_home'                        => Result::Returned,
		'is_front_page'                  => Result::Returned,
		'is_single'                      => Result::Returned,
		'is_singular'                    => Result::Returned,
		'is_page'                        => Result::Returned,
		'is_page_template'               => Result::Returned,
		'is_category'                    => Result::Returned,
		'is_tag'                         => Result::Returned,
		'is_tax'                         => Result::Returned,
		'is_author'                      => Result::Returned,
		'is_date'                        => Result::Returned,
		'is_year'                        => Result::Returned,
		'is_month'                       => Result::Returned,
		'is_day'                         => Result::Returned,
		'is_time'                        => Result::Returned,
		'is_archive'                     => Result::Returned,
		'is_search'                      => Result::Returned,
		'is_404'                         => Result::Returned,
		'is_attachment'                  => Result::Returned,
		'is_post_type_archive'           => Result::Returned,
		'is_privacy_policy'              => Result::Returned,
		'is_paged'                       => Result::Returned,
		'is_preview'                     => Result::Returned,
		'is_feed'                        => Result::Returned,
		'is_embed'                       => Result::Returned,
		'is_new_day'                     => Result::Returned,
		'is_admin'                       => Result::Returned,
		'is_customize_preview'           => Result::Returned,
		'is_multisite'                   => Result::Returned,
		'is_main_site'                   => Result::Returned,
		'is_child_theme'                 => Result::Returned,
		'is_ssl'                         => Result::Returned,
		'wp_is_mobile'                   => Result::Returned,
		'current_theme_supports'         => Result::Returned,
		'post_type_exists'               => Result::Returned,
		'taxonomy_exists'                => Result::Returned,
		'is_post_type_hierarchical'      => Result::Returned,
		'is_post_type_viewable'          => Result::Returned,

		// Settings and environment.
		'get_option'                     => Result::Returned,
		'get_theme_mod'                  => Result::Returned,
		'wp_get_theme'                   => Result::Returned,
		'wp_get_environment_type'        => Result::Returned,
	);
}
